### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by mysteryx93** [reactiveui/Splat.DI.SourceGenerator#85]
Avalonia comes with ReactiveUI and ReactiveUI comes with Splat. I'm trying to use those default tools.

What bugs me off is that Splat by default needs to manually create each object. Splat.DI.SourceGenerator is supposed to solve that problem.

Now in my project I have Avalonia.ReactiveUI and Splat.DI.SourceGenerator

SplatRegistrations is not recognized. I find no way to use this.

    SplatRegistrations.Register<IMenuUseCase, MenuUseCase>();
    SplatRegistrations.Register<IOtherDependency, OtherDependency>();

I spent several hours trying to get this to work. What am I missing?

Besides the troubles to get this setup; what are the benefits of going the Splat route vs some more established DI containers like Microsoft DI or Simple Injector?

My project file contains this

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="0.10.10" />
      <PackageReference Include="Avalonia.Desktop" Version="0.10.10" />
      
      <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="0.10.10" />
      <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.10" />
      <PackageReference Include="Avalonia.Xaml.Behaviors" Version="0.10.10.4" />
      <PackageReference Include="Splat.DependencyInjection.SourceGenerator" Version="1.1.33">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

**Comment by glennawatson** [comment]
Anything in the compile logs. SplatRegistration class gets added by the source generator. 

Also making sure you have a reference to the namespace splat.

**Comment by glennawatson** [comment]
Main advantage of the approach is dramatic speed improvements. There's no reflection like there is with Microsoft di. All the dependencies are worked out at compile time.

Normally there are in the build logs source generator failure of there is one.

**Comment by glennawatson** [comment]
What ide are you using btw. Visual studio/rider?

What platform are you developing on. Windows or Mac?

**Comment by mysteryx93** [comment]
Interesting. It works in Visual Studio 2022. It does NOT work in JetBrains Rider.

**Comment by glennawatson** [comment]
Rider should support source generators as of 2021.3 I believe.

**Comment by mysteryx93** [comment]
I'm using 2021.3.1

**Comment by glennawatson** [comment]
Try turning off resharper build in rider and see if that helps

I'll try rider again with the project as well

**Comment by mysteryx93** [comment]
That works. It's a Resharper issue then.

**Comment by mysteryx93** [comment]
Ya I got all my projects working now... looks like there's a bug in Rider but restarting it may fix the issue. May require further investigation.

**Comment by fnicks** [comment]
Hello! Can you help me? I tried to use that SourceGenerator with my SplatRegistrations. I made registrations and SplatRegistrations.SetupIOC(); in my Bootstrappers (I have few services).. When I'm trying to use them I got null exception error because they didn't resolve.. Do I need to do something like this: ConfigurationService = Locator.Current.GetService<IConfigurationService>(); and how should I use that when I have a lot of classes where I need to use that services?
